#!/usr/bin/perl
# fix the interjections in ls.nom
# NOTE that this file is hereby no longer generated!

while(<>)
{
    if (/<pos>interj/)
    {
	s|\s*<pos>interj\.</pos>||;
	my ($word, $tail) = split /\s+/;
	print ":le:$word\n:wd:$word\texclam\n" unless ($word =~ /^\s*$/);
	next if ($tail =~ /^\s*$/);
	while ($tail =~ m|<orth>([^<]*)</orth>|g)
	{
	    my $orth = $1;
	    next if ($orth =~ /^\s*$/);
	    print ":le:$orth\n:wd:$orth\texclam\n";
	}
    }
    else
    {
	print;
    }
}
