a-blatio ablatio
a-caedo acide
a-cieo acieris
a-cieo acies
a-cio acieris
a-cio acies
a-co acor
a-conitor aconiti
a-credo acredo
a-creo#1 acra
a-creo#1 acro
a-creo#1 acror
a-dedo adedo
a-dito adito
a-do ador
a-do#2 ador
a-edo#2 aedes
a-edo#2 aedis
a-equito aequitas
a-equito aequiter
a-eripio aeripes
a-erugo#1 aerugo
a-evito#1 aevitas
a-jugo#1 ajuga
a-laudo alauda
a-ligo#1 aliger
a-linquo aliqui
a-lio alia
a-lio alias
a-lio alio
a-liqueo aliqui
a-liquo aliqua
a-liquo aliquando
a-liquo aliquanto
a-liquo aliquo
a-lito aliter
a-lituro alitura
a-luto#1 aluta
a-marito amaritas
a-marito amariter
a-meto ametor
a-meto#2 ametor
a-metor ametor
a-miceo amice
a-nancio anancitis
a-palo apala
a-palo#1 apala
a-palo#2 apala
a-pico apica
a-pio apio
a-piscor apiscor
a-plano aplanes
a-quatio aquatio
a-reno#1 arena
a-ruro arura
a-scribo ascribo
a-specio aspicio
a-spicio aspicio
a-spiro aspiro
a-strigo astriger
a-stringo astringo
a-ululo aulula
a-uro auris
a-uto autor
a-utor autor
a-vento aventer
a-video avide
a-vio avia
a-volo avis
ab-arceo abarcet
ab-beo abba
ab-beo abbas
ab-caedo abcido
ab-do abdo
ab-do#2 abdo
ab-emo abemito
ab-eo#1 abeo
ab-grego abgregare
ab-hiemo abhiemo
ab-horreo abhorreo
ab-jacio abicio
ab-luto#1 ablutor
ab-oleo#1 aboleo
ab-repo arrepo
ab-rumpo abrumpo
ab-struo abstruo
ab-sum#1 absum
ab-torqueo abtorqueo
ab-uto abutor
ab-utor abutor
abs-sum#1 absum
abs-teneo abstineo
ad-aperio adaperio
ad-arceo adarce
ad-augeo adaugeo
ad-cano accano
ad-clamito acclamito
ad-colo#2 accola
ad-congero#1 accongero
ad-decet addecet
ad-ducto adductor
ad-edo adedo
ad-edo#2 adedo
ad-eo#1 adeo#1
ad-expeto adexpeto
ad-facio afficio
ad-fero affero
ad-figo affigo
ad-finio affinis
ad-flecto afflecto
ad-fligo affligo
ad-flo afflo
ad-fluento affluenter
ad-for affor
ad-frico affrico
ad-fulgeo affulgeo
ad-fundo#1 affundo
ad-fundo#2 affundo
ad-gestio#2 aggestio
ad-gnosco agnosco
ad-gradior aggredior
ad-habito adhabito
ad-horreo adhorreo
ad-indo adindo
ad-ito adito
ad-jacio adicio
ad-jubeo adjubeo
ad-labor#1 allabor
ad-lambo allambo
ad-livesco allivescit
ad-loquor alloquor
ad-monito admonitor
ad-nasco adnascor
ad-nasco annascor
ad-nascor adnascor
ad-nascor annascor
ad-nato adnato
ad-navigo adnavigo
ad-necto adnecto
ad-neo#1 anne
ad-niteo adnitendus
ad-nitor#1 annitor
ad-no#1 adnato
ad-nosco agnosco
ad-opino adopinor
ad-opinor adopinor
ad-pareo appareo
ad-parito apparitor
ad-pendo appendo
ad-penso appensor
ad-plaudo applaudo
ad-plico applico
ad-plodo applodo
ad-pono appono
ad-porto apporto
ad-prendo apprendo
ad-propero appropero
ad-propinquo appropinquo
ad-quaero acquiro
ad-quiesco adquiesco
ad-repo arrepo
ad-saturo assatura
ad-sector#2 assector
ad-sedo assedo
ad-sisto assisto
ad-soleo assoleo
ad-sto asto
ad-suesco assuesco
ad-sum#1 adsum
ad-surgo assurgo
ad-tribulo attribulo
ad-uto adutor
ad-utor adutor
ad-vereor advereor
ad-verro adverro
amb-ago ambages
amb-ago ambago
amb-edo ambedo
amb-edo#2 ambedo
amb-ito ambitor
ante-ago anteago
ante-ambulo anteambulo
ante-cesso antecessor
ante-curso antecursor
ante-dico#1 antedico
ante-dico#2 antedico
ante-eo#1 anteeo
ante-fero antefero
ante-paro#1 anteparo
ante-paro#2 anteparo
ante-po antepes
ante-rideo anterides
circum-colo#2 circumcola
circum-do circumdo
circum-do#2 circumdo
circum-ducto circumductor
circum-eo#1 circumeo
circum-fero circumfero
circum-fodio circumfodio
circum-fosso circumfossor
circum-gradior circumgredior
circum-ito circuitor
circum-jaceo circumjaceo
circum-jacio circumjacio
circum-lavo circumlavo
circum-linio circumlinio
circum-loquor circumloquor
circum-sedeo circumsideo
circum-specio circumspicio
circum-tondeo circumtondeo
circum-tremo circumtremo
circum-vento circumventor
circum-verro circumverro
co-adjuto coadjutor
co-adjutor#1 coadjutor
co-alesco coalesco
co-aresco coaresco
co-cio cocio
co-co coco
co-do coda
co-do#2 coda
co-eno coena
co-eo#1 coeo
co-liceo#1 colice
co-liceor colice
co-lineo colina
co-lio colias
co-miceo comice
co-po copa
co-po copo
co-stabilio costabilis
co-sto costa
co-uto coutor
co-utor coutor
con-caedo concaedes
con-capio#1 concapit
con-cateno concateno
con-clavo conclavo
con-colo#1 concolor
con-colo#2 concolor
con-comito concomitor
con-comitor concomitor
con-cubito concubitor
con-cubo concubo
con-custodio concustodio
con-decet condecet
con-decurio#1 condecurio
con-denseo condenseo
con-ducto conductor
con-eo#1 coeo
con-fabrico confabricor
con-fabricor confabricor
con-fabulo confabulor
con-fabulor confabulor
con-facio confacio
con-fero confero
con-fero conferte
con-fervesco confervesco
con-feto confeta
con-fibulo confibula
con-figuro configuro
con-finio confinis
con-fio conficio
con-flato conflator
con-foedero confoedero
con-frequento confrequento
con-frio confrio
con-fugo confuga
con-gestio#2 congestio
con-gratulor congratulor
con-jacio conicio
con-labor#1 collabor
con-lecto collector
con-lego#1 collega
con-libet collibet
con-libo#1 collibet
con-luceo colluceo
con-monito commonitor
con-munito communiter
con-necto connecto
con-nitor#1 connitor
con-pedo#1 compedes
con-pedo#2 compedes
con-pluo compluit
con-poto compotor
con-preco comprecor
con-precor comprecor
con-prehendo comprehendo
con-quaero conquaero
con-rugio corrugis
con-rugo corrugo
con-sacro consacro
con-saepio consaepio
con-satio#1 consatio
con-scindo conscindo
con-sepelio consepelio
con-sitio consitio
con-solido consolida
con-solido consolido
con-sopio consopio
con-sortio consortio
con-sortior consortio
con-spargo#1 conspargo
con-specto conspector
con-sponso consponsor
con-spuo conspuo
con-spurco conspurco
con-subigo consubigo
con-sueo consueo
con-sum#1 consum
con-tago contages
con-temero contemero
con-tento contemptor
con-tero contero
con-tono contonat
con-torqueo contorqueo
con-torto contortor
con-tribulo contribulo
con-tueo contueor
con-tueor contueor
con-vesco convescor
con-vitio convitio
con-voveo convoveo
con-vulnero convolnero
de-ambulo deambulo
de-armo dearmo
de-calceo decalco
de-calco decalco
de-calefacio decalefacio
de-calesco decalesco
de-carmino#1 decarmino
de-carmino#2 decarmino
de-cesso decessor
de-cieo decies
de-cio decies
de-co decas
de-co deceris
de-co decor
de-curo decures
de-curro decurro
de-curto decurto
de-duco deduco
de-ducto deductor
de-eo#1 deeo
de-erro#1 deerro
de-fatisco defatiscor
de-fero defero
de-fio defio
de-forio deforis
de-fraudo defraudo
de-fremo defremo
de-frico defrico
de-fruor defruor
de-fungor defungor
de-glabro deglabro
de-glubo deglubo
de-grandino degrandinat
de-gravo degravo
de-grunnio degrunnio
de-hisco dehisco
de-indo deinde
de-ito deitas
de-jacio deicio
de-jugo#2 dejugis
de-lanio#1 delaniare
de-lavo delavo
de-libro delibro
de-liquo deliquo
de-lito delitor
de-meio demeio
de-mordeo demordeo
de-moveo demoveo
de-nasco denascor
de-nascor denascor
de-operio deoperio
de-pacisco depaciscor
de-paciscor depaciscor
de-pango depango
de-pecto depecto
de-pleo depleo
de-polio#1 depolio
de-potio#2 depotitur
de-potior#1 depotitur
de-prenso deprensa
de-promo depromo
de-pudeo depudet
de-pulpo depulpo
de-purgo depurgo
de-queo deque
de-saevio desaevio
de-sicco desicco
de-signo designo
de-spicio despicio
de-spico despica
de-sponso desponsor
de-sugo desugo
de-sum#1 desum
de-supo desuper
de-tendo detendo
de-tento detentor
de-torno detorno
de-uto deutor
de-utor deutor
de-vasto devasto
de-vello devello
de-verso devorsor
de-vesco devescor
dis-bucino dibucino
dis-colo#1 discolor
dis-colo#2 discolor
dis-crucio discrucio
dis-fateor diffiteor
dis-fero differo
dis-fido diffido
dis-findo diffindo
dis-gestio#2 digestio
dis-gnosco dignosco
dis-lecto dilector
dis-lorico dilorico
dis-moveo dimoveo
dis-neo#1 dine
dis-nosco dignosco
dis-pando#1 dispando
dis-pando#2 dispando
dis-partio#2 dispartio
dis-partior dispartio
dis-pergo dispergo
dis-plodo displodo
dis-po dispando
dis-pono dispono
dis-pudeo dispudet
dis-rapio diripio
dis-rego dirigo
dis-repto direptor
dis-rigo dirigo
dis-rumpo disrumpo
dis-seco disseco
dis-sipo dissipo
dis-suo dissuo
dis-taedeo distaedet
dis-tracto distractor
dis-verto divorto
dis-viso divisor
dis-vitio divitia
ex-cieo excio
ex-consulo exconsularis
ex-creo excreo
ex-cubito excubitor
ex-dico#2 edico
ex-dito editor
ex-ducto eductor
ex-edo exedo
ex-edo exesto
ex-edo#2 exedo
ex-eo#1 exeo
ex-fero effero#1
ex-fervesco effervesco
ex-fio effio
ex-fleo effleo
ex-fodio effodio
ec-freno effreno
ex-freno effreno
ex-frico effrico
ex-gestio#2 egestio
ex-gurgito exgurgito
ex-jacio eicio
ex-labo elabor
ex-labor#1 elabor
ex-lateo elate
ex-latito elatites
ex-laudo elaudare
ex-liceo#1 elices
ex-liceor elices
ex-marcesco emarcesco
ex-molio emolior
ex-molior emolior
ex-molo#1 emolo
ex-moveo emoveo
ex-nasco enascor
ex-nascor enascor
ex-neco eneco
ex-nitesco enitesco
ex-nitor#1 enitor
ex-notesco enotesco
ex-ordior exordior
ex-orior exorior
ex-patior expatior
ex-plico explicate
ex-plico explico
ex-presso expressor
ex-pungo expungo
ex-rapio eripio
ex-reor eremus
ex-reor eres
ex-repto ereptor
ex-rogo exrogare
ex-ruo eruo
ex-scindo exscindo
ex-seco exseco
ex-sector#2 exsector
ex-spargo#1 exspargo
ex-stinguo exstinguo
ex-torto extortor
ex-tremo extremo
ex-ungo exungo
ex-verso eversor
ex-versor eversor
ex-video evideor
in-acerbo inacerbo
in-aresco inaresco
in-assero#1 inassero
in-assero#2 inassero
in-audio inaudio
in-auspico inauspicato
in-beo imber
in-calo incalanto
in-censeo incense
in-censeo#1 incense
in-cohibeo incohibeo
in-comito incomitem
in-comito incomiter
in-comitor incomiter
in-commeo incomma
in-communio#1 incommunis
in-como#1 incomis
in-credo incredendus
in-credo incredundus
in-cubo incubo
in-cresco incresco
in-doleo indoles
in-dolo#1 indoles
in-ducto inductor
in-eo#1 ineo
in-fateor infiteri
in-fatigo infatigo
in-fero infero
in-flecto inflecto
in-fligo infligo
in-for infandus
in-for infer
in-for inferne
in-frequento infrequenter
in-generasco ingenerasco
in-gestio#2 ingestio
in-gradior ingredior
in-humano inhumano
in-jugo#2 injugis
in-ludo illudo
in-merito#2 immerito
in-mobilito immobilitas
in-munito immunitas
in-obscuro inobscuro
in-orior inorior
in-orior inoris
in-paeniteo impaenitendus
in-parento imparentem
in-parito impariter
in-pasco impascor
in-pascor impascor
in-pigreo impigre
in-plico implico
in-po impes
in-provideo improvide
in-proviso#2 improviso
in-pulso impulsor
in-punior impunis
in-rado inrado
in-rideo irrideo
in-rumpo irrumpo
in-saepio insaepio
in-saluto insalutaris
in-signo insigno
in-similo insimilo
in-sitio insitio
in-somnio insomnia
in-sum#1 insum
in-supo insuper
in-temero intemerandus
in-termino intermino
in-testo intestato
in-timeo intime
in-tuto intuta
in-tuto#2 intuta
in-unguo inunguo
in-urgeo inurgeo
in-vecto invector
in-vento inventor
in-vilito invilito
in-violo inviolo
inter-amento interamenta
inter-aperio interaperio
inter-caedo intercisi
inter-calceo intercalco
inter-calco intercalco
inter-cesso intercessor
inter-dicto interdictor
inter-do interdo
inter-do#2 interdo
inter-edo interest
inter-emo interimo
inter-eo#1 intereo
inter-facio interfacio
inter-fio interfio
inter-fugio interfugio
inter-fundo interfundo
inter-lucesco interlucesco
inter-mino intermino
inter-neo#1 interne
inter-no#1 interna
inter-no#1 internas
inter-polio#1 interpolis
inter-premo interpremo
inter-sileo intersileo
inter-sum#1 intersum
inter-trituro intertritura
inter-vento interventor
inter-verto intervorto
intro-eo#1 introeo
ob-acerbo obacerbat
ob-caedo occaedes
ob-cano occano
ob-coepio occoepi
ob-curro occurro
ob-duco obduco
ob-dulcesco obdulcesco
ob-edo obedo
ob-edo#2 obedo
ob-eo#1 obeo
ob-esco obescet
ob-esito obesitas
ob-facio officio
ob-fero offero
ob-flo offla
ob-for offa
ob-fuco offuco
ob-fundo#1 offundo
ob-fundo#2 offundo
ob-herbesco obherbescere
ob-irasco obirascor
ob-irascor obirascor
ob-ito obiter
ob-jurgo objurgo
ob-lineo oblino
ob-linio oblinio
ob-liqueo oblique
ob-lito oblitor
ob-necto obnectere
ob-nitor#1 obnitor
ob-pingo oppingo
ob-pono oppono
ob-porto opporto
ob-presso oppressor
ob-ruo obruo
ob-saluto obsalutare
ob-servio observito
ob-sto obsto
ob-stupeo obstupendus
ob-stupesco obstupesco
ob-sum#1 obsum
ob-torpeo obtorpeo
ob-tracto obtractat
ob-tueo obtueor
ob-tueor obtueor
ob-violo obviolo
op-fero offero
per-aresco peraresco
per-audio peraudiendus
per-caedo percaedo
per-cedo#1 percedo
per-celo perceler
per-cerno percernis
per-clamo perclamo
per-cludo percludo
per-como#1 percomis
per-cupio percupio
per-dito perditor
per-domito perdomitor
per-domo perdomo
per-eo#1 pereo
per-excrucio perexcrucio
per-exilio perexilis
per-extimesco perextimesco
per-fero perfero
per-fingo perfingo
per-fosso perfossor
per-frico perfrico
per-frigeo perfrigeo
per-fugo perfuga
per-fungor perfungor
per-grandio pergrandis
per-indo perinde
per-insignio perinsignis
per-libet perlibet
per-libo#1 perlibet
per-liceo#1 perlicet
per-liceor perlicet
per-lineo perlino
per-miro permirandus
per-miror permirandus
per-mollio permollis
per-moneo permoneo
per-morior permorior
per-moro permoror
per-moror#1 permoror
per-moror#2 permoror
per-multo#2 permulto
per-narro pernarro
per-no#1 perna
per-nosco pernosco
per-nuntio pernuntio
per-odi perodi
per-opto peroptato
per-ploro perploro
per-po perpes
per-suo persuo
per-taedeo pertaedeo
per-taedeo pertaedet
per-tumesco pertumesco
per-ungo perungo
per-urgeo perurgeo
per-valeo pervaleo
per-vecto pervector
per-vento perventor
prae-acuo praeacuo
prae-aequo praeaequo
prae-carpo praecarpo
prae-celo praeceler
prae-cesso praecessor
prae-co praeco
prae-coepio praecoepi
prae-crudesco praecrudesco
prae-curso praecursor
prae-eo#1 praeeo
prae-fero praefero
prae-gigno praegigno
prae-grandio praegrandis
prae-jacio praejacio
prae-lecto praelector
prae-monito praemonitor
prae-oro praeoro
prae-ostendo praeostendo
prae-patior praepatior
prae-plecto#2 praeplecto
prae-po praepes
prae-possum praepossum
prae-propero praepropero
prae-repto praereptor
prae-sido praesidero
prae-specio praespicio
prae-spicio praespicio
prae-stabilio praestabilis
prae-stinguo praestinguo
prae-sum#1 praesum
prae-suo praesuo
prae-tento praetempto
prae-ungo praeungo
prae-varico praevarico
prae-vento praeventor
prae-verno praevernat
praeter-ago praeterago
praeter-eo#1 praetereo
praeter-fero praeterfero
praeter-ito praeterita
praeter-rado praeterrado
praeter-sum#1 praetersum
praeter-veho praetervehor
pro-aucto proauctor
pro-calo procalare
pro-capio#1 procapis
pro-cero proceres
pro-cito#2 procitant
pro-cito#2 procitare
pro-co proceres
pro-consulo proconsularis
pro-creo procreo
pro-dito proditor
pro-emineo proemineo
pro-fateor profiteor
pro-fero profero
pro-fluento profluenter
pro-fugo profuga
pro-fundito profunditas
pro-gigno progigno
pro-geniculo progeniculo
pro-lugeo prolugeo
pro-mello promellere
pro-monstro promonstra
pro-mutuo promutuor
pro-mutuo#2 promutuor
pro-mutuor promutuor
pro-neo#1 prone
pro-patior propatior
pro-plasmo proplasma
pro-po propes
pro-polio#1 propolis
pro-purgo propurgo
pro-reto proreta
pro-rigo proriga
pro-sapio prosapies
pro-sector#2 prosector
pro-sedo proseda
pro-sopio prosopis
pro-specio prospicio
pro-spico prospica
pro-sumo prosumo
pro-vecto provector
pro-vegeo provegeo
pro-vendo provendo
pro-verto proverto
prod-eo#1 prodeo
prod-ito proditor
re-bullio rebullio
re-calefacio recalefacio
re-canto recanto
re-cingo recingo
re-claudo reclaudo
re-claudo#1 reclaudo
re-claudo#2 reclaudo
re-creo recreo
re-eo#1 redeo
re-fero refero
#re-fero refert
re-frico refrico
re-fugo refuga
re-galeo regales
re-liceo#1 reliceor
re-liceor reliceor
re-lucesco relucesco
re-moro remores
re-mundo remundo
re-nancio renancitur
re-nancior renancitur
re-nasco renascor
re-nascor renascor
re-nitor#1 renitor
re-pecto repecto
re-po repandus
re-presso repressor
re-salvo resalvare
re-socio resociandus
re-sum#1 resum
re-teneo retineo
re-tero retero
re-tero retero
re-vello revello
re-vereor reverendus
re-vereor revereor
re-vero revera
re-verto reverto
re-verto revorto
re-vivisco revivisco
re-volvo revolvo
red-dito redditor
red-eo#1 redeo
red-operio redoperio
retro-specio retrospicio
se-caleo secale
se-co secundae
se-co secundum
se-curito securitas
se-ducto seductor
se-lecto selector
se-lenio selenitis
se-libro selibra
se-lineo selinas
se-mentior sementis
se-meo semet
se-nato senator
se-pio sepia
se-pio sepio
se-rapio serapias
se-reneo serene
se-rivo seriva
se-simo#1 sesima
sub-adjuvo subadjuva
sub-aduno subaduno
sub-alo subalare
sub-alo subalaris
sub-cesso successor
sub-co succo
sub-curso succursor
sub-doleo subdole
sub-edo subedo
sub-edo#2 subedo
sub-eo#1 subeo
sub-erigo suberigo
sub-fero suffero
sub-for suffes
sub-gestio#2 suggestio
sub-grandio suggrandis
sub-inanio subinanis
sub-influo subinfluo
sub-irasco subirascor
sub-irascor subirascor
sub-lateo sublate
sub-limito sublimitas
sub-limito sublimiter
sub-lugeo sublugeo
sub-malo summalis
sub-meo summa
sub-meo summas
sub-minio#1 summinia
sub-mitto summitto
sub-moto summotor
sub-necto subnecto
sub-oculo subocularis
sub-pedo#1 suppedo
sub-pedo#2 suppedo
sub-presso suppressor
sub-pudeo suppudet
sub-rapio surripio
sub-rego surgo
sub-ringor surringor
sub-ruo surruo
sub-sipo subsipere
sub-sum#1 subsum
sub-uro suburo
sub-vado#1 subvades
sub-vado#2 subvades
sub-vereor subvereor
super-curro supercurro
super-effero#2 supereffero
super-egredior superegredior
super-emorior superemorior
super-facio superficies
super-fero superfero
super-figo superfigo
super-fio superfio
super-fugio superfugio
super-gradior supergradior
super-gradior supergredior
super-impleo superimpleo
super-inspicio superinspicio
super-intento superintentor
super-labo superlabor
super-labor#1 superlabor
super-molo#1 supermolaris
super-neo#1 superne
super-no#1 supernas
super-perspicio superperspicio
super-ruo superruo
super-stringo superstringo
super-sum#1 supersum
super-vacuo supervacuo
trans-dito traditor
trans-duco traduco
trans-ducto traductor
trans-eo#1 transeo
trans-fero transfero
trans-fugo transfuga
trans-ito transitor
trans-jungo transjungo
trans-loquor traloquor
trans-moveo transmoveo
trans-sero#1 transsero
trans-sero#2 transsero
trans-sero#3 transsero
trans-sitio transitio
trans-sumo transsumo
trans-supplodo transsero
trans-vendo transvendo
