#define VOWCONTRACTS	"rule_files/vowcontr.table"
#define CONSEUPH	"rule_files/conseuph.table"
#define STEMTYPES	"rule_files/stemtypes.table"
#define DERIVTYPES	"rule_files/derivtypes.table"
#define DOMAINLIST	"rule_files/domainlist.table"
#define PPASSLIST	"rule_files/ppasslist.table"
#define RAWPBLIST	"rule_files/raw_preverbs.table"
