#include "filttab.h"
#define lengthof( X ) (sizeof X / sizeof X[0] )

filt_tab beta_tab[] =  {
	" ?",	ELLIPSIS,
	"!",	ELLIPSIS,
	"a",	alpha,
	"a/",	a_AC,
	"a\\",	a_GR,
	"a=",	a_CI,
	"a(",	a_RO,
	"a(/",	a_RO_AC,
	"a(\\",	a_RO_GR,
	"a(=",	a_RO_CI,
	"a)",	a_SM,
	"a)/",	a_SM_AC,
	"a)\\",	a_SM_GR,
	"a)=",	a_SM_CI,
		
	"a?",	alpha,
	"a/?",	a_AC,
	"a\\?",	a_GR,
	"a=?",	a_CI,
	"a(?",	a_RO,
	"a(/?",	a_RO_AC,
	"a(\\?",	a_RO_GR,
	"a(=?",	a_RO_CI,
	"a)?",	a_SM,
	"a)/?",	a_SM_AC,
	"a)\\?",	a_SM_GR,
	"a)=?",	a_SM_CI,
		
	"*a?",	ALPHA,
	"*=?a",	A_CI,
	"*(?a",	A_RO,
	"*(/?a",	A_RO_AC,
	"*(\\?a",	A_RO_GR,
	"*(=?a",	A_RO_CI,
	"*)?a",	A_SM,
	"*)/?a",	A_SM_AC,
	"*)\\?a",	A_SM_GR,
	"*)=?a",	A_SM_CI,
		
	"*a",	ALPHA,
	"*=a",	A_CI,
	"*(a",	A_RO,
	"*(/a",	A_RO_AC,
	"*(\\a",	A_RO_GR,
	"*(=a",	A_RO_CI,
	"*)a",	A_SM,
	"*)/a",	A_SM_AC,
	"*)\\a",	A_SM_GR,
	"*)=a",	A_SM_CI,
		
	"a|",	a_IS,
	"a/|",	a_AC_IS,
	"a\\|",	a_GR_IS,
	"a=|",	a_CI_IS,
	"a(|",	a_RO_IS,
	"a(/|",	a_RO_AC_IS,
	"a(\\|",	a_RO_GR_IS,
	"a(=|",	a_RO_CI_IS,
	"a)|",	a_SM_IS,
	"a)/|",	a_SM_AC_IS,
	"a)\\|",	a_SM_GR_IS,
	"a)=|",	a_SM_CI_IS,
		
	"b",	beta,
	"b?",	beta,
	"*b",	BETA,
	"*b?",	BETA,

	"g",	gamma,
	"g?",	gamma,
	"*g",	GAMMA,
	"*g?",	GAMMA,

	"d",	delta,
	"d?",	delta,
	"*d",	DELTA,
	"*d?",	DELTA,
		
	"*e",	EPSILON,
	"*(e",	E_RO,
	"*(/e",	E_RO_AC,
	"*(\\e",	E_RO_GR,
	"*)e",	E_SM,
	"*)/e",	E_SM_AC,
	"*)\\e",	E_SM_GR,
		
	"*e?",	EPSILON,
	"*(?e",	E_RO,
	"*(/?e",	E_RO_AC,
	"*(\\?e",	E_RO_GR,
	"*)?e",	E_SM,
	"*)/?e",	E_SM_AC,
	"*)\\?e",	E_SM_GR,
		

	"e/",	e_AC,
	"e\\",	e_GR,
	"e(",	e_RO,
	"e(/",	e_RO_AC,
	"e(\\",	e_RO_GR,
	"e)",	e_SM,
	"e)/",	e_SM_AC,
	"e)\\",	e_SM_GR,
		
	"e",	epsilon,
	"e?",	epsilon,
	"e/?",	e_AC,
	"e\\?",	e_GR,
	"e(?",	e_RO,
	"e(/?",	e_RO_AC,
	"e(\\?",	e_RO_GR,
	"e)?",	e_SM,
	"e)/?",	e_SM_AC,
	"e)\\?",	e_SM_GR,
		
	"z",	zeta,
	"z?",	zeta,
	"*z",	ZETA,
	"*z?",	ZETA,
		
	"*h",	HTA,
	"*/h",	H_AC,
	"*\\h",	H_GR,
	"*=h",	H_CI,
	"*(h",	H_RO,
	"*(/h",	H_RO_AC,
	"*(\\h",	H_RO_GR,
	"*(=h",	H_RO_CI,
	"*)h",	H_SM,
	"*)/h",	H_SM_AC,
	"*)\\h",	H_SM_GR,
	"*)=h",	H_SM_CI,
		
	"*h?",	HTA,
	"*/?h",	H_AC,
	"*\\?h",	H_GR,
	"*=?h",	H_CI,
	"*(?h",	H_RO,
	"*(/?h",	H_RO_AC,
	"*(\\?h",	H_RO_GR,
	"*(=?h",	H_RO_CI,
	"*)?h",	H_SM,
	"*)/?h",	H_SM_AC,
	"*)\\?h",	H_SM_GR,
	"*)=?h",	H_SM_CI,
		
	"h",	hta,
	"h?",	hta,
	"h/?",	h_AC,
	"h\\?",	h_GR,
	"h=?",	h_CI,
	"h(?",	h_RO,
	"h(/?",	h_RO_AC,
	"h(\\?",	h_RO_GR,
	"h(=?",	h_RO_CI,
	"h)?",	h_SM,
	"h)/?",	h_SM_AC,
	"h)\\?",	h_SM_GR,
	"h)=?",	h_SM_CI,
		
	"h/",	h_AC,
	"h\\",	h_GR,
	"h=",	h_CI,
	"h(",	h_RO,
	"h(/",	h_RO_AC,
	"h(\\",	h_RO_GR,
	"h(=",	h_RO_CI,
	"h)",	h_SM,
	"h)/",	h_SM_AC,
	"h)\\",	h_SM_GR,
	"h)=",	h_SM_CI,
		
	"h|",	h_IS,
	"h/|",	h_AC_IS,
	"h\\|",	h_GR_IS,
	"h=|",	h_CI_IS,
	"h(|",	h_RO_IS,
	"h(/|",	h_RO_AC_IS,
	"h(\\|",	h_RO_GR_IS,
	"h(=|",	h_RO_CI_IS,
	"h)|",	h_SM_IS,
	"h)/|",	h_SM_AC_IS,
	"h)\\|",	h_SM_GR_IS,
	"h)=|",	h_SM_CI_IS,
		
	"q",	qeta,
	"q?",	qeta,
	"*q",	QETA,
	"*q?",	QETA,
		
	"*i?",	IOTA,
	"*/?i",	I_AC,
	"*\\?i",	I_GR,
	"*=?i",	I_CI,
	"*(?i",	I_RO,
	"*(/?i",	I_RO_AC,
	"*(\\?i",	I_RO_GR,
	"*(=?i",	I_RO_CI,
	"*)?i",	I_SM,
	"*)/?i",	I_SM_AC,
	"*)\\?i",	I_SM_GR,
	"*)=?i",	I_SM_CI,
		
	"*i",	IOTA,
	"*/i",	I_AC,
	"*\\i",	I_GR,
	"*=i",	I_CI,
	"*(i",	I_RO,
	"*(/i",	I_RO_AC,
	"*(\\i",	I_RO_GR,
	"*(=i",	I_RO_CI,
	"*)i",	I_SM,
	"*)/i",	I_SM_AC,
	"*)\\i",	I_SM_GR,
	"*)=i",	I_SM_CI,
		
	"i",	iota,
	"i?",	iota,
	"i/?",	i_AC,
	"i\\?",	i_GR,
	"i+?",	i_DI,
	"i/+?",	i_AC_DI,
	"i\\+?",	i_GR_DI,
	"i=?",	i_CI,
	"i(?",	i_RO,
	"i(/?",	i_RO_AC,
	"i(\\?",	i_RO_GR,
	"i(=?",	i_RO_CI,
	"i)?",	i_SM,
	"i)/?",	i_SM_AC,
	"i)\\?",	i_SM_GR,
	"i)=?",	i_SM_CI,
		
	"i/",	i_AC,
	"i\\",	i_GR,
	"i+",	i_DI,
	"i/+",	i_AC_DI,
	"i\\+",	i_GR_DI,
	"i=",	i_CI,
	"i(",	i_RO,
	"i(/",	i_RO_AC,
	"i(\\",	i_RO_GR,
	"i(=",	i_RO_CI,
	"i)",	i_SM,
	"i)/",	i_SM_AC,
	"i)\\",	i_SM_GR,
	"i)=",	i_SM_CI,
		
	"k?",	kappa,
	"*k?",	KAPPA,
	"l?",	lambda,
	"*l?",	LAMBDA,
	"m?",	mu,
	"*m?",	MU,
	"n?",	nu,
	"*n?",	NU,
	"c?",	ci,
	"*c?",	CI,
		
	"k",	kappa,
	"l",	lambda,
	"m",	mu,
	"n",	nu,
	"c",	ci,

	"*k",	KAPPA,
	"*l",	LAMBDA,
	"*m",	MU,
	"*n",	NU,
	"*c",	CI,
		
	"o",	omicron,
	"o?",	omicron,
	"o/?",	o_AC,
	"o\\?",	o_GR,
	"o(?",	o_RO,
	"o(/?",	o_RO_AC,
	"o(\\?",	o_RO_GR,
	"o)?",	o_SM,
	"o)/?",	o_SM_AC,
	"o)\\?",	o_SM_GR,
		
	"o/",	o_AC,
	"o\\",	o_GR,
	"o(",	o_RO,
	"o(/",	o_RO_AC,
	"o(\\",	o_RO_GR,
	"o)",	o_SM,
	"o)/",	o_SM_AC,
	"o)\\",	o_SM_GR,
		
	"*o?",	OMICRON,
	"*/?o",	O_AC,
	"*\\?o",	O_GR,
	"*(?o",	O_RO,
	"*(/?o",	O_RO_AC,
	"*(\\?o",	O_RO_GR,
	"*)?o",	O_SM,
	"*)/?o",	O_SM_AC,
	"*)\\?o",	O_SM_GR,
		
	"*o",	OMICRON,
	"*/o",	O_AC,
	"*\\o",	O_GR,
	"*(o",	O_RO,
	"*(/o",	O_RO_AC,
	"*(\\o",	O_RO_GR,
	"*)o",	O_SM,
	"*)/o",	O_SM_AC,
	"*)\\o",	O_SM_GR,
		
	"p",	pi,
	"p?",	pi,
	"*p?",	PI,
	"*p",	PI,

	"r(",	r_RO,
	"r(?",	r_RO,
	"r)",	r_SM,
	"r)?",	r_SM,
	"r",	rho,
	"r?",	rho,
	"*r?",	RHO,
	"*r",	RHO,
	"*(r",	R_RO,
	"*(?r",	R_RO,
	"*)r",	R_SM,
	"*)?r",	R_SM,
		
	"s",	sigma,
	"s?",	sigma,
	"s1",	sigma,
	"s2",	sigma,
	"s3",	sigma,

	"*s?",	SIGMA,
	"*s",	SIGMA,
	"*s1",	SIGMA,
	"*s2",	SIGMA,
	"*s3",	SIGMA,
		
	"t",	tau,
	"t?",	tau,
		
	"*t",	TAU,
	"*t?",	TAU,
		
	"*u?",	UPSILON,
	"*/?u",	U_AC,
	"*\\?u",	U_GR,
	"*=?u",	U_CI,
	"*(?u",	U_RO,
	"*(/?u",	U_RO_AC,
	"*(\\?u",	U_RO_GR,
	"*(=?u",	U_RO_CI,
	"*)?u",	U_SM,
	"*)/?u",	U_SM_AC,
	"*)\\?u",	U_SM_GR,
	"*)=?u",	U_SM_CI,
		
	"*u",	UPSILON,
	"*/u",	U_AC,
	"*\\u",	U_GR,
	"*=u",	U_CI,
	"*(u",	U_RO,
	"*(/u",	U_RO_AC,
	"*(\\u",	U_RO_GR,
	"*(=u",	U_RO_CI,
	"*)u",	U_SM,
	"*)/u",	U_SM_AC,
	"*)\\u",	U_SM_GR,
	"*)=u",	U_SM_CI,
		
	"u",	upsilon,
	"u?",	upsilon,

	"u/?",	u_AC,
	"u\\?",	u_GR,
	"u+?",	u_DI,
	"u/+?",	u_AC_DI,
	"u\\+?",	u_GR_DI,
	"u=?",	u_CI,
	"u(?",	u_RO,
	"u(/?",	u_RO_AC,
	"u(\\?",	u_RO_GR,
	"u(=?",	u_RO_CI,
	"u)?",	u_SM,
	"u)/?",	u_SM_AC,
	"u)\\?",	u_SM_GR,
		
	"u/",	u_AC,
	"u\\",	u_GR,
	"u+",	u_DI,
	"u/+",	u_AC_DI,
	"u\\+",	u_GR_DI,
	"u=",	u_CI,
	"u(",	u_RO,
	"u(/",	u_RO_AC,
	"u(\\",	u_RO_GR,
	"u(=",	u_RO_CI,
	"u)",	u_SM,
	"u)/",	u_SM_AC,
	"u)\\",	u_SM_GR,
	"u)=",	u_SM_CI,
		
	"f",	fi,
	"*f",	FI,

	"x",	xi,
	"*x",	XI,

	"y",	yi,
	"*y",	YI,
		
	"f?",	fi,
	"*f?",	FI,

	"x?",	xi,
	"*x?",	XI,

	"y?",	yi,
	"*y?",	YI,
		
	"*w?",	WMEGA,
	"*/?w",	W_AC,
	"*\\?w",	W_GR,
	"*=?w",	W_CI,
	"*(?w",	W_RO,
	"*(/?w",	W_RO_AC,
	"*(\\?w",	W_RO_GR,
	"*(=?w",	W_RO_CI,
	"*)?w",	W_SM,
	"*)/?w",	W_SM_AC,
	"*)\\?w",	W_SM_GR,
	"*)=?w",	W_SM_CI,
		
	"*w",	WMEGA,
	"*/w",	W_AC,
	"*\\w",	W_GR,
	"*=w",	W_CI,
	"*(w",	W_RO,
	"*(/w",	W_RO_AC,
	"*(\\w",	W_RO_GR,
	"*(=w",	W_RO_CI,
	"*)w",	W_SM,
	"*)/w",	W_SM_AC,
	"*)\\w",	W_SM_GR,
	"*)=w",	W_SM_CI,
		
	"w",	wmega,
	"w?",	wmega,

	"w/?",	w_AC,
	"w\\?",	w_GR,
	"w=?",	w_CI,
	"w(?",	w_RO,
	"w(/?",	w_RO_AC,
	"w(\\?",	w_RO_GR,
	"w(=?",	w_RO_CI,
	"w)?",	w_SM,
	"w)/?",	w_SM_AC,
	"w)\\?",	w_SM_GR,
	"w)=?",	w_SM_CI,
		
	"w/",	w_AC,
	"w\\",	w_GR,
	"w=",	w_CI,
	"w(",	w_RO,
	"w(/",	w_RO_AC,
	"w(\\",	w_RO_GR,
	"w(=",	w_RO_CI,
	"w)",	w_SM,
	"w)/",	w_SM_AC,
	"w)\\",	w_SM_GR,
	"w)=",	w_SM_CI,
		
		
	"w|",	w_IS,
	"w/|",	w_AC_IS,
	"w\\|",	w_GR_IS,
	"w=|",	w_CI_IS,
	"w(|",	w_RO_IS,
	"w(/|",	w_RO_AC_IS,
	"w(\\|",	w_RO_GR_IS,
	"w(=|",	w_RO_CI_IS,
	"w)|",	w_SM_IS,
	"w)/|",	w_SM_AC_IS,
	"w)\\|",	w_SM_GR_IS,
	"w)=|",	w_SM_CI_IS,
	
};

beta_length()
{
	return( lengthof( beta_tab ) );
}

beta_size()
{
	return( sizeof beta_tab );
}
